# 安全扫描配置
app:
  security:
    dependency-check:
      # 报告路径
      report-path: target/dependency-check-report
      
      # 高危漏洞阈值 (CVSS 评分)
      high-severity-threshold: 7.0
      
      # 通知配置
      notification:
        enabled: true
        recipients:
          "security@myweb.com",
          "admin@myweb.com"

      # 扫描配置
      scan:
        # 是否在构建时自动扫描
        auto-scan-on-build: true
        
        # 是否跳过测试依赖
        skip-test-scope: false
        
        # 数据库自动更新
        auto-update-database: true
        
        # 扫描超时时间（分钟）
        timeout-minutes: 30
        
        # 支持的报告格式
        report-formats:
          - HTML
          - JSON
          - XML
          - CSV
          
      # 抑制配置
      suppression:
        # 抑制文件路径
        file-path: owasp-suppressions.xml
        
        # 是否启用抑制
        enabled: true
        
        # 抑制规则审查周期（天）
        review-cycle-days: 90

# 邮件配置（用于安全报告通知）
spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}

# 日志配置
logging:
  level:
    com.myweb.website_core.application.service.security.IPS.virusprotect.DependencySecurityService: INFO
    org.owasp.dependencycheck: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,security-scan
  endpoint:
    security-scan:
      enabled: true
  info:
    env:
      enabled: true