# 安全策略配置
app:
  security:
    # 密码策略
    password-policy:
      min-length: 8
      max-length: 128
      require-uppercase: true
      require-lowercase: true
      require-digit: true
      require-special-char: true
      bcrypt-strength: 12
      special-chars: "!@#$%^&*()_+-=[]{}|;:,.<>?"
      history-count: 5
    
    # 账户锁定策略
    account-lock:
      max-failed-attempts: 5
      lock-duration-minutes: 15
      captcha-threshold: 3
    
    # 验证码配置
    captcha:
      length: 6
      expiration-minutes: 5
      type: mixed
    
    # 会话管理
    session:
      timeout-minutes: 30
      single-session: true
      cleanup-interval-minutes: 10
      max-concurrent-sessions: 1
    
    # TOTP配置
    totp:
      issuer: MyWeb
      time-step-seconds: 30
      allowed-time-skew: 1
      secret-length: 32
    
    # CSRF配置
    csrf:
      enabled: true
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN
      parameter-name: _csrf
      cookie-path: /blog
      cookie-max-age: 7200  # 2小时
      cookie-http-only: false
      cookie-secure: true
      token-cache-expiration-hours: 2

# 日志配置
logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"