# 病毒扫描配置
# 符合GB/T 22239-2019二级等保要求的恶意代码防范机制

app:
  security:
    virus-scan:
      # 病毒扫描引擎类型 (mock, clamav)
      engine: mock
      
      # 是否启用病毒扫描
      enabled: true
      
      # 扫描超时时间（秒）
      timeout: 30
      
      # 最大扫描文件大小
      max-file-size: 50MB
      
      # 扫描失败时是否阻止上传
      block-on-scan-failure: false
      
      # 扫描引擎不可用时是否阻止上传
      block-on-engine-unavailable: false
      
      # ClamAV配置
      clamav:
        host: localhost
        port: 3310
        connection-timeout: 5000
        read-timeout: 30000
      
      # 隔离配置
      quarantine:
        # 隔离目录路径
        path: ${java.io.tmpdir}/myweb-quarantine
        
        # 隔离文件保留天数
        retention-days: 30
        
        # 隔离区最大大小
        max-size: 100MB
        
        # 是否启用隔离功能
        enabled: true
      
      # 告警配置
      alert:
        # 是否启用告警
        enabled: true
        
        # 是否启用邮件告警
        email-enabled: true
        
        # 管理员邮箱
        admin-email: admin@myweb.com
        
        # 最小告警威胁级别 (NONE, LOW, MEDIUM, HIGH, CRITICAL)
        min-threat-level: MEDIUM

# 异步任务配置
spring:
  task:
    execution:
      pool:
        # 核心线程数
        core-size: 2
        # 最大线程数
        max-size: 10
        # 队列容量
        queue-capacity: 100
        # 线程名前缀
        thread-name-prefix: virus-scan-
      shutdown:
        # 优雅关闭等待时间
        await-termination: true
        await-termination-period: 60s

# 日志配置
logging:
  level:
    com.myweb.website_core.application.service.security: DEBUG
    fi.solita.clamav: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,virus-scan
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: myweb-virus-scan
    export:
      prometheus:
        #enabled: true