-- 初始化博客文章数据
-- INSERT INTO blog_post (title, content, author, created_at) VALUES
-- (
--     '欢迎来到我的博客',
--     '这是我的第一篇博客文章。在这里，我将分享我的技术心得和学习经验。',
--     '管理员',
--     CURRENT_TIMESTAMP
-- ),
-- (
--     'Spring Boot 开发指南',
--     'Spring Boot 是一个基于 Spring 框架的快速开发框架，它简化了 Spring 应用的配置和部署过程。',
--     '张三',
--     CURRENT_TIMESTAMP
-- ),
-- (
--     '数据库优化技巧',
--     'PostgreSQL 是一个功能强大的开源关系型数据库，在企业级应用中广泛使用。',
--     '李四',
--     CURRENT_TIMESTAMP
-- );